image: $REGISTRY_URL/k8s/docker:19.03.12-dind-tools

variables:
  DOCKER_HOST: tcp://localhost:2376
  DOCKER_TLS_CERTDIR: "/certs"
  DOCKER_CERT_PATH: "/certs/client"
  DOCKER_TLS_VERIFY: 1
  DOCKER_DAEMON_OPTIONS: --insecure-registry=$REGISTRY_URL --experimental=true

before_script:
  - until docker info; do sleep 2; done
  - docker login $REGISTRY_URL --username $HARBOR_USERNAME --password $HARBOR_PASSWORD

services:
  - name: $REGISTRY_URL/k8s/docker:19.03.12-dind-tools
    entrypoint: ["sh", "-c", "dockerd-entrypoint.sh $DOCKER_DAEMON_OPTIONS"]

stages:
  - build

build:
  stage: build
  script:
    - bash ./build.sh
  only:
    - master
  tags:
    - k8s-ci
