version: '3.8'

services:
  nexusdata:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: nexusdata:1.0
    container_name: nexusdata
    restart: unless-stopped
    ports:
      - "8000:8000"

    volumes:
      - /Users/yinbenxin/.paddlenlp/:/root/.paddlenlp/
