version: '3.8'

services:
  nexusdata:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: nexusdata:1.0
    container_name: nexusdata
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - HOST=0.0.0.0
      - PORT=8000
      - WORKERS=1  # 先降低worker数量，确保模型能正常加载
      - QUEUE_MAX_SIZE=1000
      - TASK_TIMEOUT=3000
      - TASK_RETENTION_DAYS=30
      - MODEL_PATH=/tmp/model/
      - EMBEDDING_MODEL_PATH=/tmp/model/Conan-embedding-v1
      - RERANK_MODEL_PATH=/tmp/model/gte-multilingual-reranker-base
      - INFO_EXTRACT_MODEL_PATH=/tmp/model/uie-medium
      - EMBEDDING_SMELL_ZH=/tmp/model/bge-small-zh
      - HANDLE_URL = http://192.168.101.122:61916/callback

    volumes:
      - /tmp/model/:/tmp/model/
      - /Users/yinbenxin/.cache/:/root/.cache/

