version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: datanexus
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: modapp
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U datanexus -d modapp"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    environment:
      DATABASE_URL: postgresql://datanexus:123@db:5432/modapp
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data: