version: '3.8'

services:
  nexusdata:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: nexusdata:1.0
    container_name: nexusdata
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - HOST=0.0.0.0
      - PORT=8000
      - WORKERS=1  # 先降低worker数量，确保模型能正常加载
      - QUEUE_MAX_SIZE=1000
      - TASK_TIMEOUT=3000
      - TASK_RETENTION_DAYS=30
      - MODEL_PATH=/app/models
      - EMBEDDING_MODEL_PATH=/app/models/Conan-embedding-v1
      - RERANK_MODEL_PATH=/app/models/gte-multilingual-reranker-base
      - INFO_EXTRACT_MODEL_PATH=/app/models/uie-medium
      - EMBEDDING_SMELL_ZH=/app/models/bge-small-zh
    volumes:
      - /Users/yinbenxin/git/model:/app/models