version: '3.8'

services:
  nexusdata:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: nexusdata:latest
    container_name: nexusdata
    restart: unless-stopped
    ports:
      - "8000:8000"
      - "8001:6379"
    environment:
      - REDIS_URL=redis://localhost:6379/0
      - HOST=0.0.0.0
      - PORT=8000
      - WORKERS=4
      - QUEUE_MAX_SIZE=100
      - TASK_TIMEOUT=300
      - TASK_RETENTION_DAYS=30
      - MODEL_PATH=/app/models
      - EMBEDDING_MODEL_PATH=/app/models/Conan-embedding-v1
      - RERANK_MODEL_PATH=/app/models/gte-multilingual-reranker-base
      - INFO_EXTRACT_MODEL_PATH=/app/models/uie-medium
      - EMBEDDING_SMELL_ZH=/app/models/bge-small-zh
    volumes:
      - /Users/yinbenxin/git/model:/app/models